spring:
  datasource:
    username: nils
    password: nils
    url: jdbc:postgresql://localhost:5432/hierarchical_mapping
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/liquibase/updates.xml